name: nasa_pod
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  intl: ^0.18.0
  retrofit: ^4.0.1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
